# Generated by Django 4.1.3 on 2023-03-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(blank=True, max_length=255, null=True)),
                ('attack_rm', models.IntegerField(blank=True, null=True)),
                ('attack_op', models.IntegerField(blank=True, null=True)),
                ('dattack_rm', models.IntegerField(blank=True, null=True)),
                ('dattack_op', models.IntegerField(blank=True, null=True)),
                ('sont_rm', models.IntegerField(blank=True, null=True)),
                ('sont_op', models.IntegerField(blank=True, null=True)),
                ('sofft_rm', models.IntegerField(blank=True, null=True)),
                ('sofft_op', models.IntegerField(blank=True, null=True)),
                ('pos_rm', models.IntegerField(blank=True, null=True)),
                ('pos_op', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
