# Generated by Django 4.1.3 on 2023-03-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='attack_op',
            new_name='counterAttack_opp',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='attack_rm',
            new_name='counterAttack_rm',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='dattack_op',
            new_name='fouls_opp',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='dattack_rm',
            new_name='fouls_rm',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='pos_op',
            new_name='offsides_opp',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='pos_rm',
            new_name='offsides_rm',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='sofft_op',
            new_name='possession_opp',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='sofft_rm',
            new_name='possession_rm',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='sont_op',
            new_name='shootsOffTarget_opp',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='sont_rm',
            new_name='shootsOffTarget_rm',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='shootsOnTarget_opp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='shootsOnTarget_rm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
