# Generated by Django 4.1.3 on 2023-03-09 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_attack_op_matchresult_counterattack_opp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='added On'),
            preserve_default=False,
        ),
    ]
