# Generated by Django 4.1.3 on 2023-03-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('gamesPlayed', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('dob', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('pob', models.CharField(blank=True, max_length=255, null=True)),
                ('prefFoot', models.BooleanField(default=1)),
                ('pfp', models.ImageField(default='static/images/players/default.jpg', upload_to='static/images/players')),
            ],
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
