# Generated by Django 4.1.3 on 2023-03-09 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_player_delete_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='prefFoot',
            new_name='isPreferredFootRight',
        ),
    ]
