# Generated by Django 4.1.3 on 2023-03-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_preffoot_player_ispreferredfootright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
