# Generated by Django 4.1.3 on 2023-03-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_player_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaendarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(blank=True, max_length=255, null=True)),
                ('taskIcon', models.ImageField(default='static/images/tasks/default.svg', upload_to='static/images/tasks')),
                ('taskDate', models.DateField()),
            ],
        ),
    ]
