# Generated by Django 4.1.3 on 2023-03-12 17:17

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_claendartask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claendartask',
            name='taskIcon',
        ),
        migrations.CreateModel(
            name='TaskIconSetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskIcon', models.ImageField(default='static/images/tasks/default.svg', upload_to=home.models.iconNameChange)),
                ('taskFor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.claendartask')),
            ],
        ),
    ]
