# Generated by Django 4.1.3 on 2023-03-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_task_remove_claendartask_taskname_claendartask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskiconsetter',
            name='taskFor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.task'),
        ),
    ]
