# Generated by Django 4.1.3 on 2023-03-12 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_taskiconsetter_taskfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claendartask',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.task'),
        ),
        migrations.AlterField(
            model_name='claendartask',
            name='taskDate',
            field=models.DateField(unique=True),
        ),
    ]
