# Generated by Django 4.1.3 on 2023-03-12 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_claendartask_task_alter_claendartask_taskdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='claendartask',
            name='taskIcon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.taskiconsetter'),
        ),
    ]
