# Generated by Django 4.1.3 on 2023-03-12 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_calendar_task_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='calendar',
        ),
        migrations.AddField(
            model_name='claendartask',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.calendar'),
        ),
    ]
