# Generated by Django 4.1.3 on 2023-03-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_task_calendar_claendartask_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claendartask',
            name='calendar',
        ),
    ]
