# Generated by Django 4.1.3 on 2023-03-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_claendartask_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFetch', models.DateField(blank=True, null=True)),
                ('taskFetch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.claendartask')),
            ],
        ),
    ]
