# Generated by Django 4.1.3 on 2023-03-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_fetchtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claendartask',
            name='taskDate',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='FetchTask',
        ),
    ]
