# Generated by Django 4.1.3 on 2023-03-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_claendartask_taskdate_delete_fetchtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskiconsetter',
            name='taskFor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.task'),
        ),
    ]
