# Generated by Django 4.1.3 on 2023-03-12 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_taskiconsetter_taskfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claendartask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.task'),
        ),
        migrations.AlterField(
            model_name='claendartask',
            name='taskIcon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.taskiconsetter'),
        ),
    ]
