# Generated by Django 4.1.3 on 2023-03-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_claendartask_task_alter_claendartask_taskicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claendartask',
            name='taskDate',
            field=models.DateField(unique=True),
        ),
    ]
