# Generated by Django 4.1.3 on 2023-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_claendartask_taskdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
