# Generated by Django 4.1.3 on 2023-03-16 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_player_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('vidImg', models.CharField(blank=True, max_length=5000, null=True)),
                ('vidLink', models.CharField(blank=True, max_length=5000, null=True)),
                ('whichMatch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.matchresult')),
            ],
        ),
    ]
