# Generated by Django 4.1.3 on 2023-03-17 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_apikey_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session1', models.TimeField(unique=True)),
                ('session2', models.TimeField(unique=True)),
                ('session3', models.TimeField(unique=True)),
                ('sessionFor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.claendartask')),
            ],
        ),
    ]
