# Generated by Django 4.1.3 on 2023-03-17 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_dailysession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysession',
            old_name='session1',
            new_name='session1_end',
        ),
        migrations.RenameField(
            model_name='dailysession',
            old_name='session2',
            new_name='session1_start',
        ),
        migrations.RenameField(
            model_name='dailysession',
            old_name='session3',
            new_name='session2_end',
        ),
        migrations.AddField(
            model_name='dailysession',
            name='session2_start',
            field=models.TimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysession',
            name='session3_end',
            field=models.TimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysession',
            name='session3_start',
            field=models.TimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
