# Generated by Django 4.1.3 on 2023-03-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_session1_dailysession_session1_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysession',
            name='session1_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dailysession',
            name='session1_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dailysession',
            name='session2_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dailysession',
            name='session2_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dailysession',
            name='session3_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='dailysession',
            name='session3_start',
            field=models.TimeField(),
        ),
    ]
