# Generated by Django 4.1.3 on 2023-03-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_dailysession_session1_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysession',
            name='session1_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dailysession',
            name='session2_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dailysession',
            name='session3_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
