# Generated by Django 4.1.3 on 2023-03-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_dailysession_session1_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(blank=True, max_length=500, null=True)),
                ('ex1', models.CharField(blank=True, max_length=500, null=True)),
                ('ex1_time', models.IntegerField()),
                ('ex2', models.CharField(blank=True, max_length=500, null=True)),
                ('ex2_time', models.IntegerField()),
                ('ex3', models.CharField(blank=True, max_length=500, null=True)),
                ('ex3_time', models.IntegerField()),
            ],
        ),
    ]
