# Generated by Django 4.1.3 on 2023-03-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysession',
            name='session1_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session1', to='home.session'),
        ),
        migrations.AlterField(
            model_name='dailysession',
            name='session2_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session2', to='home.session'),
        ),
        migrations.AlterField(
            model_name='dailysession',
            name='session3_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session3', to='home.session'),
        ),
    ]
